In [1]:
import numpy as np
#import matplotlib.pylab as plt

In [66]:
def LogisticRegression(x, y, lr, epochs):
    def sigmoid(z):
        return 1/(1+(np.exp(-z)))
    m = np.zeros(x.shape[1])
    c = 0
    for _ in range(epochs):
        z = np.dot(x,m)+c
        pred = sigmoid(z)
        error = pred - y # error is always pred - actual, if we use actual - pred then we have to use - sign in gw and gb.
        print(error)

        gw = 1/len(x)*(np.dot(x.T,error)) # we dont have to use sum because dot do that already, if we use x.T * error then we have to do sum.
        gb = 1/len(x)*np.sum(error)
        if np.any(np.isnan(gw)) or np.any(np.isnan(gb)) or np.any(np.isinf(gw)) or np.any(np.isinf(gb)): #for handling nan and infinte error
            break
        m-=lr*gw
        c-=lr*gb
    return m,c,pred


In [67]:
X = np.array([[0.1, 0.2], [0.4, 0.5], [0.7, 0.8]])  # Feature matrix (3 samples, 2 features)
y = np.array([0, 1, 1])

In [68]:
m,c,pred = LogisticRegression(X,y,0.01,100)

[ 0.5 -0.5 -0.5]
[ 0.50055   -0.4991875 -0.498925 ]
[ 0.50109764 -0.49837799 -0.49785362]
[ 0.50164294 -0.49757145 -0.49678586]
[ 0.50218589 -0.49676789 -0.49572171]
[ 0.50272651 -0.4959673  -0.49466117]
[ 0.5032648  -0.49516967 -0.49360423]
[ 0.50380077 -0.49437499 -0.49255089]
[ 0.50433443 -0.49358325 -0.49150115]
[ 0.50486579 -0.49279445 -0.49045501]
[ 0.50539485 -0.49200859 -0.48941245]
[ 0.50592161 -0.49122564 -0.48837347]
[ 0.5064461  -0.49044562 -0.48733807]
[ 0.50696831 -0.4896685  -0.48630625]
[ 0.50748825 -0.48889429 -0.48527799]
[ 0.50800594 -0.48812297 -0.4842533 ]
[ 0.50852137 -0.48735454 -0.48323217]
[ 0.50903455 -0.48658899 -0.48221458]
[ 0.5095455  -0.48582631 -0.48120055]
[ 0.51005422 -0.4850665  -0.48019005]
[ 0.51056071 -0.48430954 -0.47918309]
[ 0.51106499 -0.48355543 -0.47817966]
[ 0.51156706 -0.48280417 -0.47717976]
[ 0.51206694 -0.48205573 -0.47618336]
[ 0.51256462 -0.48131013 -0.47519048]
[ 0.51306011 -0.48056734 -0.4742011 ]
[ 0.51355343 -0.47982736 -0.47321522

In [69]:
#plt.scatter(X,y)
z = np.dot(X,m)+c
#plt.plot(len(pred),pred,color='red')

In [70]:
z

array([0.17862895, 0.27256721, 0.36650547])

In [71]:
pred

array([0.54418625, 0.56716755, 0.58986342])